### ISSUE TITLE
document.currentScript.src is returning a null value

### ISSUE THREAD

**Issue by Justynooi** [Arcadier/Plug-In-support#10]
**Your issue/question:**
I want to use this function called “getAdminToken()” below. The Plug-In’s script runs on the buyer portal and I want to call a PHP file found in the `user` folder of my zip file. But for that I need the URL of my plug-in which include the package ID of the plug-in; it looks like this:

<p style="text-align: center"> “{marketplace-name}.arcadier.io/user/plugins/{package-ID}/verification.php”</p>

This is how I am getting the URL above:

```javascript
$(document).ready(function(){

	var scriptSrc = document.currentScript.src;
	var packagePath = scriptSrc.replace('/scripts/scripts.js', '').trim(); 

function getAdminToken(){
		$.ajax({
			"url": packagePath + "/verification.php",
			"method": "POST",
			"async": false,
			success: function(response){
				tok = response;
				console.log(tok);
			}
		});
	}
});
```

**What you expect to achieve**
I want scriptSrc to be able to store this: “{marketplace-name}.arcadier.io/user/plugins/{package-ID}”. If that works I will be able to call my PHP file in getAdminToken().

**What happens instead**
`document.currentScript.src` keeps saying it cannot read .src of `null`.

**Screenshots**
<img width="623" alt="Screen Shot 2019-09-02 at 5 00 55 PM" src="https://user-images.githubusercontent.com/52450226/64102805-46a39600-cda3-11e9-855a-7207a631ff6b.png">

**Your system/software details**
MacBook Pro using Google Chrome.

**Comment by Arcadier** [comment]
Try using wrapping your function in a setInterval():

```javascript
setInterval(function(){ 
var scriptSrc = document.currentScript.src; 
//rest of your code 
},2000);
```

**Comment by Justynooi** [comment]
But what if the time taken to execute my code takes more than 2000ms? Not that it will, but I prefer not to arbitrarily estimate the worst-case scenario of the latency.

**Comment by Arcadier** [comment]
In that case then try wrapping your whole script in this way:

```javascript
(function(){
	var scriptSrc = document.currentScript.src;
	//rest of your code
})();
```

**Comment by Justynooi** [comment]
It works! Thank you for your help!

**Comment by wilmaribg** [comment]
Remove mode 'use sctrict' from you script

**Comment by bronzwikgk** [comment]
Am facing the same issues, despite wrapping it up in the interval Time.
