### ISSUE TITLE
debugging stripe API calls using PHP

### ISSUE THREAD

**Issue by jakusan** [Arcadier/Plug-In-support#11]
**Your issue/question:**
I'm unable to know what's wrong with my StripeAPI call because there’s no way for me to receive error messages from buggish calls

**What you expect to achieve**
Are there any tools can you recommend to be able to log my errors, or do you have any tool that can do this.

**What happens instead**
Nothing

**Screenshots**

**Your system/software details**
Macbook pro Mojave

**Comment by Arcadier** [comment]
I'm assuming you're building a plug-in. Have you tried doing it the way we did it in our [Plug-In Billing Engine](https://github.com/Arcadier/Plug-In-Billing-Engine/blob/master/Subscription%20Based%20Billing/license/license.php).

we did this, in one instance:

```php
$subscription = \Stripe\Subscription::retrieve($subId);
file_put_contents("../admin/error.php", $subscription);
```
Whatever the response of the Stripe API, it was logged in an empty, pre-created php file. Then, just navigate to its link to see its error message.

**Comment by jakusan** [comment]
How do i navigate to this file???

**Comment by Arcadier** [comment]
If your code runs on admin side, and is found outside your scripts folder then go to this link:

``https://{marketplace}.arcadier.io/admin/plugins/{packageID}/error_log.php``

If your code runs on the user side, then navigate this:

``https://{marketplace}.arcadier.io/user/plugins/{packageID}/error_log.php``
