### ISSUE TITLE
pre-Checkout - Generate Invoice API does not work properly

### ISSUE THREAD

**Issue by renixnahc** [Arcadier/Plug-In-support#13]
**Describe the bug**

**To Reproduce**
1. Use Node.js to create add an item to cart using API.
2. Use Checkout - Generate Invoice and Orders from Cart and use `cartItemID` from Step 1 to generate an invoice.

```javascript
var request = require("request");

var options = { 
  method: 'POST',
  url: 'https://inkit.sandbox.arcadier.io/api/v2/users/e6e67a9d-cc28-46cf-8f8e-d1abc5b76851/invoices/carts',
  headers: { 
     'Authorization': 'Bearer {token}',
     'Content-Type': 'application/json' 
  },
  body: { 
'5ffcd888-e2d0-4604-9dc5-d2a32d9c0227' 
  },
  json: true };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
```

**Expected behavior**
I expect to see something similar to what’s shown in the [documentation](https://apiv2.arcadier.com/?version=latest#4b0bc4da-201c-472e-8deb-1a2e1099f908), but instead I get an error 500. What am I doing wrong?

**Screenshots**

**Desktop (please complete the following information):**
Running on MacOS Mojave, using Chrome

**Comment by Arcadier** [comment]
This is wrong:
```javascript
body: { 
   '5ffcd888-e2d0-4604-9dc5-d2a32d9c0227' 
}
```

The body takes an array:
```javascript
body: [ 
   '5ffcd888-e2d0-4604-9dc5-d2a32d9c0227' 
]
```

**Comment by renixnahc** [comment]
Oh okay that works, but it doesn’t really make sense for this one API to work like this. Usually JSON requests are in the form of:
```JSON
 { 
   "id": [
      { 
        "id1": "...", 
        "id2": "..."
      }
   ]
}
```

**Comment by Arcadier** [comment]
That’s true, we will consider this as an improvement. Thanks for giving us this kinda feedback! :)
