### ISSUE TITLE
Create User API doesn't seem to need confirm password.

### ISSUE THREAD

**Issue by thuytienpt** [Arcadier/Plug-In-support#14]
**Describe the bug**
Put the password and different confirm password, it still creates a new user.

**Expected behavior**
The response should be 
```
{
    "Code": 400,
    "Message": "The passwords do not seem to match.",
    "InnerErrors": null
}
```

**Screenshots**
<img width="627" alt="Screen Shot 2019-09-12 at 3 17 10 PM" src="https://user-images.githubusercontent.com/12761217/64762395-b1598c00-d570-11e9-9ef7-0ac02006ac98.png">
<img width="930" alt="Screen Shot 2019-09-12 at 3 16 10 PM" src="https://user-images.githubusercontent.com/12761217/64762863-7f94f500-d571-11e9-86e4-9bb06c4decc5.png">

**Desktop:**
 - Browser : Chrome

**Comment by Arcadier** [comment]
hey thuytienpt, thanks for reporting that. 
You have used `confirm_password` instead of `ConfirmPassword` in the request body. See our API documentation.

But nonetheless, it should not work. We're working on fixing this and will update here and on the documentation once its done

**Comment by rachaelchin** [comment]
Hi @thuytienpt ,

![image (1)](https://user-images.githubusercontent.com/74695639/99753636-8f1eaf00-2b21-11eb-9637-fcb0f9fbd0f3.png)
We have confirmed that this issue has been fixed!

Thank you and happy coding!

Regards,
Rachael from the product marketing team
