### ISSUE TITLE
Trying to create a stripe Charge

### ISSUE THREAD

**Issue by ianortega** [Arcadier/Plug-In-support#15]
```php
$customer = \Stripe\Customer::create([
                    'email' => $email,
                    'source' => $source,
                ]);

$charge = \Stripe\Charge::create([
                  'amount' => 2500,
                  'currency' => 'SGD',
                  'customer' => $customer->id,
                  'source' => $source,
                  'receipt_email' => $email
```

**What you expect to achieve**
I want to create a one time charge after creating a customer on stripe, using PHP on your side. Why is it not working? There’s no way for me to debug because of the way your system is. I cant debug anything.

**What happens instead**
I know that im successfully creating the customer because im logging any errors in error_log.php

**Screenshots**

**Your system/software details**

Mac OSX, Chrome

**Comment by Arcadier** [comment]
you can't use `$source` twice. Anyway you dont need `$source` in the body to create a charge
