### ISSUE TITLE
Can't see my newly created plugin

### ISSUE THREAD

**Issue by abid-rafiq** [Arcadier/Plug-In-support#17]
Hello Team,

I tried creating a plugin, but it seems that my plugin is not visible on my marketplace, I also cannot make it public as it's a test plugin. Attached are the 2 screenshots if you can help me with this.

Thanks in Advance.

![screencapture-dashboard-sandbox-arcadier-io-package-edit-f8fbae36-deae-42b5-b0aa-c794da181a3e-2020-01-30-11_56_21](https://user-images.githubusercontent.com/43639053/73475269-d7fa5100-43b1-11ea-8f15-17b62cc0a476.png)
![screencapture-dashboard-sandbox-arcadier-io-package-2020-01-30-11_59_22](https://user-images.githubusercontent.com/43639053/73475272-d92b7e00-43b1-11ea-8ff1-e1f9243bbd6c.png)

**Comment by rishikarthikeyan27** [comment]
Hey Abid,
So one problem might be the fact that no zip was uploaded for the plugin.

When I created a private plugin for my marketplace and saved it without uploading any zip file, my plugin wasn't visible in my marketplace. 
Let me show you what I mean

![Annotation 2020-04-22 124753](https://user-images.githubusercontent.com/59817452/79942014-67d30700-8498-11ea-871a-0c98040f51e1.png)

![Annotation 2020-04-22 124832](https://user-images.githubusercontent.com/59817452/79942030-6f92ab80-8498-11ea-9581-0649910cc613.png)

![Annotation 2020-04-22 124859](https://user-images.githubusercontent.com/59817452/79942041-76212300-8498-11ea-9fc3-08ea80d2bc29.png)

_However when a zip file was added to the plugin, then it was visible_

![Annotation 2020-04-22 124939](https://user-images.githubusercontent.com/59817452/79942063-8b964d00-8498-11ea-9a9a-16235b79417f.png)

![Annotation 2020-04-22 125006](https://user-images.githubusercontent.com/59817452/79942070-90f39780-8498-11ea-8499-5a4bb294f17d.png)

![Annotation 2020-04-22 125035](https://user-images.githubusercontent.com/59817452/79942078-9650e200-8498-11ea-818f-95b07c0fadff.png)

Upload any zip file to the plugin and try again

**Comment by abid-rafiq** [comment]
Thanks for your reply, but you've been too late, I fixed this on my end. I am closing this issue now.
Thanks again.
In the meantime, could you please check these 2 issues that I created as well?
https://github.com/Arcadier/Developer-Community-Support/issues/20
https://github.com/Arcadier/Developer-Community-Support/issues/19
