### ISSUE TITLE
Making endpoint 'http://{{your-marketplace}}/api/v2/items/' works with GUID

### ISSUE THREAD

**Issue by abid-rafiq** [Arcadier/Plug-In-support#18]
Hello There,
I used Arcadier APIs to get all the items now issue is that API is not providing me Item Detail URL, and hence when I try to generate it needs an Internal Item ID but Arcadier just sends me the GUID.

![Issue_1](https://user-images.githubusercontent.com/43639053/76698035-f2695f00-66bf-11ea-8da3-6e4964476d4f.png)
![Issue_2](https://user-images.githubusercontent.com/43639053/76698038-f85f4000-66bf-11ea-88b8-67646a12de48.png)

Either you can provide me a new object property in the same API as **DetailURL** or **ItemInternalId**

Or

Handle from backend for GUID as well.

**Comment by ArcadierPteLtd** [comment]
So, let me understand properly - your aim is to get the item detail page's URL via API? And the same thing for categories?

**Comment by abid-rafiq** [comment]
Yes, Exactly. 
So maybe there are 2 options, either, 
- You send me an item detail page URL in API.
- Or {Domain}/User/Item/Detail/{Category}/{GUID} make this URL work with GUID as last parameter. because as for now the last parameter only accepts Internal Item Id (6 lettered) that I don't get from API.

**Comment by abid-rafiq** [comment]
And Yes same thing for category.

**Comment by ArcadierPteLtd** [comment]
I checked with the developers. The next update (6th April) to Arcadier should allow your second point 

> Or {Domain}/User/Item/Detail/{Category}/{GUID} make this URL work with GUID as last parameter.

for items, but not categories. I have suggested that the category experience be the same, but this needs to be discussed whether it makes sense to have it pulled up our current priority list.

**Comment by abid-rafiq** [comment]
Thanks, I appreciate your effort.
Can you suggest a workaround for categories? As I get GUID and parameter CategoryId accepts internal ID.

Also, check the below URL.
https://drive.google.com/file/d/1_pB1YUyahYp7ryg7ek1PrQEQRCZZt0sd/view

**TimeToFirstByte** for getting category is approx 15 seconds, that is too much.

**Comment by abid-rafiq** [comment]
2 more little things, if you could, I need Merchant Profile Image in GetAllItems Endpoint, as for now I am getting null. Example Given

- I need a merchant image the same as you've in the Search page. 
- Can you also please remove these consoles from our marketplace? I can see it on Search page


![image](https://user-images.githubusercontent.com/43639053/78451921-bbc0ac00-76a1-11ea-9959-48023bdbdab0.png)

**Comment by abid-rafiq** [comment]
Endpoint that I want in.

![image](https://user-images.githubusercontent.com/43639053/78452028-646f0b80-76a2-11ea-89d7-b9fd8886d6d9.png)

**Comment by rachaelchin** [comment]
Hi @abid-rafiq , 

I have changed this post into an enhancement request about making GUID to work with the API. Since this enhancement has been released, I shall close this thread. 

The other issue about Media returning null value in the GET all items endpoint. I have created another thread for it. You may track it here [Media returns as null in GET all items endpoint #29](https://github.com/Arcadier/Developer-Community-Support/issues/29) instead.

Thanks and regards,
Rachael from product marketing team

**Comment by rachaelchin** [comment]
Hi @abid-rafiq, 

I have answered your second query in this [thread](https://github.com/Arcadier/Developer-Community-Support/issues/29 ) instead.

Thanks,
Rachael from the product marketing team
