### ISSUE TITLE
Page is reloading infinitely, due to Language Dropdown

### ISSUE THREAD

**Issue by abid-rafiq** [Arcadier/Plug-In-support#20]
Here is the video of how to reproduce the bug.

https://drive.google.com/file/d/1YLUr837UGTVvcAq381uZCj2GQsewOFgL/view

However, I went in-depth and find out that the jquery plugin that is being used for the custom dropdown has a bug on their repo regarding auto-selection on initialization, I believe you need to upgrade the version of the external jquery plugin that you are using.

https://github.com/prashantchaudhary/ddslick/issues/10

**Comment by ArcadierPteLtd** [comment]
Page was reloading due to an error 500 caused by the reset password flow;
That has already been addressed. Do let us know if you are still facing issues. It might be due to customisations.

Current jQuery library used on Arcadier's template is 3.5.1
