### ISSUE TITLE
Some sorting params not working

### ISSUE THREAD

**Issue by infinitey** [Arcadier/Plug-In-support#21]
**Describe the bug**
This is regarding "GET Search for items - Params in URL" endpoint. Sorting doesn't work for params "-created-" and 'name'.

**To Reproduce**
https://ourmarketplacename.arcadier.io/api/v2/items?pageSize=15&pageNumber=1&-created
https://ourmarketplacename.arcadier.io/api/v2/items?pageSize=15&pageNumber=1&name

**Expected behavior**
Expected the item list to be sorted by created date in descending order.
Expected the item list to be sorted by created date in alphabetical order.

**Platform**
Custom Mobile App development (iOS & Android)

**Additional context**
Platform X sandbox and production
Documentation reference: https://apiv2.arcadier.com/?version=latest#c6d3c581-2556-4cb0-a7f1-daed8733f9fd

**Comment by rishikarthikeyan27** [comment]
Hello

_So actually try using this URL for sorting by created date in descending order_
https://{{your-marketplace}}.arcadier.io/api/v2/items?sort=-created

_and for sorting by name_
https://{{your-marketplace}}.arcadier.io/api/v2/items?sort=name 

You have to use "sort" before entering the parameter, then it works perfectly

**Comment by infinitey** [comment]
Thank you for the reply! The documentation URL example should be updated to reflect the use of sort param.
