### ISSUE TITLE
Is it possible to use Custom Code (JS) on Vendor Sign Up Page on Marketplace

### ISSUE THREAD

**Issue by abid-rafiq** [Arcadier/Plug-In-support#22]
I wanted to use the Custom Code JS to addClass and had to add some additional static paragraph, but it seems like Custom code is not working on this specific page.

![image](https://user-images.githubusercontent.com/43639053/80176679-d0de8a00-8612-11ea-8258-e5d912d3f1dd.png)

**Comment by ArcadierPteLtd** [comment]
Yes it is possible, however you have to make a request through the ticket system to enable the code on your login.
There is a process to this to ensure that you are aware of potential risks you are taking with enabling scripts running on the login input page

**Comment by abid-rafiq** [comment]
Thanks, @ArcadierPteLtd,
