### ISSUE TITLE
Can not see product details in new sandbox marketplace

### ISSUE THREAD

**Issue by alexdelgado0792** [Arcadier/Plug-In-support#23]
**Describe the bug**
While trying to see product details url, page load but redirect to this search url each time.

**To Reproduce**
1. Search a product to buy
2. Click on it to see the details
3. Page load but go to search by key words url

Also trying to go directly to item details url this redirect to search url.
https://towa.sandbox.arcadier.io/User/Item/Detail/Mercurial/66376

**Comment by ArcadierPteLtd** [comment]
If the product details URL is redirecting you to the search URL when you try to access it; it means that the item no longer exists on the marketplace or is inactive.
