### ISSUE TITLE
PHP Plugins on Sandbox returning false always with CURL request

### ISSUE THREAD

**Issue by abid-rafiq** [Arcadier/Plug-In-support#26]
Hello Team,

I recently noticed that my plugin stopped working and keep returning false from every PHP CURL on my sandbox environment. I figured out it started happening on 30th August after 4:00 PM PKT, I carried a couple of test by creating new plugins and check but all the plugins that use PHP CURL requests started returning null or false.

Below are some example screenshots:

Sandbox URL:
https://testhitch.sandbox.arcadier.io

![image](https://user-images.githubusercontent.com/43639053/92018060-14d65e00-ed6e-11ea-98af-17eba983f7a0.png)

![image](https://user-images.githubusercontent.com/43639053/92018212-49e2b080-ed6e-11ea-8333-79a4150c1662.png)

![image](https://user-images.githubusercontent.com/43639053/92018275-6252cb00-ed6e-11ea-9616-343722f07f37.png)

Even simpler CURL request return false or null every time.

and the Arcadier based Coupon Code Generator Plugin is also not working on a sandbox, it's working on Live Marketplace

![image](https://user-images.githubusercontent.com/43639053/92018726-f45ad380-ed6e-11ea-871b-83ec09581994.png)

Please assist as soon as possible.

**Comment by ArcadierPteLtd** [comment]
Issue has been resolved on Sandbox
