### ISSUE TITLE
Some of the Categories does not show up item list

### ISSUE THREAD

**Issue by abid-rafiq** [Arcadier/Plug-In-support#28]
**Describe the bug**
I can see that 2 of my marketplace's Category List page are showing empty content.

**To Reproduce**
1. Go to 'https://www.hitchplanner.com/user/search/SearchByKeywords?CategoryId=105180&category=Bali%20Weddings'  or 'https://www.hitchplanner.com/user/search/SearchByKeywords?CategoryId=97948&category=Venue'
2. Page loads with empty content
3. If check the console log there are some Latitude issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/43639053/98584644-fb124380-22e7-11eb-927e-5ae9682326be.png)

**Comment by rachaelchin** [comment]
Hi abid-rafiq, 

I have checked with the customer service team, we have found that this issue happens with items without the location id. The team has fixed the issue and it should be working now. 

Regards,
Rachael from the Product Marketing team
