### ISSUE TITLE
Payment Acceptance Error Page

### ISSUE THREAD

**Issue by Chloe-blue** [Arcadier/Plug-In-support#3]
**Describe the bug**
Hi, I have changed the mandatory payment from Paypal to Stripe in the admin dashboard. Then I tried to login as a merchant and link that merchant's stripe account to the marketplace. But I get an error page.

**To Reproduce**
As above

**Expected behavior**
I have verified and reverified my API keys and redirect URI's nothing seems to be wrong so it should let me link my merchant account on stripe.

**Screenshots**
![Error Page Stripe](https://user-images.githubusercontent.com/49679456/57288813-cdde4700-70ec-11e9-9036-28aec6edf5c6.png)

Regards,
Chloe

**Comment by Arcadier** [comment]
Hey Chloe,

If you are extremely sure that your Public/Secret Keys and the redirect URI's have no mistake in them then it might be a problem on your Stripe dashboard. Make sure that Stripe itself knows the redirect URI and has it in its list.

Just to make sure, here is the step-by-step instruction. So, as an Admin:

* Login to you marketplace -> Payments and Transactions tab -> Configure Payments -> Click on link account for Stripe
* Click on Login to Stripe. Login to your Administrator's Stripe account.
* On the Stripe Dashboard, on the left panel, just below "Developers", make sure the toggle for "View Test Data" is off/set to the left/grey.
* Go to "Settings" completely at the bottom.
* In the "Stripe Apps" panel, go to "Connect".
* You will then see the "Live Mode Client ID". Copy the ID, it looks something like this: ca_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
* Go to you back to your Admin Dashboard, and paste it in the "Production Client ID" field.
* Still on your admin dashboard, copy your redirect URL.
* Go back to your Stripe Dashboard. Under the Live Client ID, there is the Redirects section. To the right, there is a button called "Add URI". Paste the redirect URL you copied from the Admin Dashboard, and lclick on "Add URI" to save it. It should appear in the list of redirect URIs in the center.
* Next, click on Developers on the left panel; it will drop down. Click on API Keys.
* You will see a table containing a Publishable Key, and its Token. Copy the token. It starts with a "pk".
* Go back to your Admin Dashboard, scroll up and paste it in the Live Publishable Key field. 
* Go back to your Stripe Dashboard, for the Secret Key click on Reveal live key token. Copy that token. It starts with an "sk". You can now close your stripe dashboard window.
* Go back to your Admin Dashboard and paste that token in the Live Secret Key  field.
* Click on every "Save" button.

That's all that's necessary for the Admin side. Your merchant should be able to link his/her Stripe account when onboarding.
If this does not work, my Skype ID is tanoo.joyekurun. Happy to help you by voice.

Regards,
Tanoo

**Comment by Chloe-blue** [comment]
Thank you Tanoo, this seems to have worked. The problem was really the URI was missing in the Stripe account. I appreciate the step by step direction as it really helped!

**Comment by Arcadier** [comment]
Hey Chloe, you're welcome anytime.
-Tanoo
