### ISSUE TITLE
Authentication API error

### ISSUE THREAD

**Issue by Chloe-blue** [Arcadier/Plug-In-support#4]
**Describe the bug**
I tried to use your Authentication API as per the instructions, but I get this error:
```json
{ 
 "error": "invalid_client"
}
```

**To Reproduce**
On postman:
1. URL: https://inkit.sandbox.arcadier.io/token
2. JSON request body:
```json
{ 
 "client_id": "my client ID",
 "client_secret": "my client secret",
 "grant_type": "client_credentials",
 "scope": "admin"
}
```

**Expected behavior**
I don't know what I should be receiving exactly, but I expect a response with the admin token

**Screenshots**
![json](https://user-images.githubusercontent.com/49679456/57291957-23b5ed80-70f3-11e9-8f83-d5b08418338f.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Postman: v7.0.9

**Comment by Arcadier** [comment]
Hey Chloe,

Try using `x-www-form-urlencoded` instead of `application/json`

**Comment by Chloe-blue** [comment]
That worked, thanks a lot.
