### ISSUE TITLE
Bearer + token in JS not working

### ISSUE THREAD

**Issue by Chloe-blue** [Arcadier/Plug-In-support#5]
**Describe the bug**
Hello Arcadier, 
I have an issue with JS. I used the Authentication API, got the token, and added "Bearer" before it to use to authenticate with other API's, but it keeps saying "Authorisation was denied."

**To Reproduce**
This was my code:
```javascript
var get_token = {
 "url": "https://" + baseURL + "/token",
 "method": "POST",
 "headers": {
   "Content-Type": "application/x-www-form-urlencoded"
 },
 "data": {
   "client_id": "",
   "client_secret": "",
   "grant_type": "client_credentials",
   "scope": "admin"
 }
};
	
$.ajax(get_token).done(function(admin_token) {
  token = "Bearer " + admin_token.access_token;
}
```
What am I doing wrong?
P.S: baseURL was already declared to be = inkit.sandbox.arcadier.io

**Comment by Arcadier** [comment]
Hey Chloe, after trying your code we think this might solve the issue:
```javascript
token = "Bearer " + JSON.stringify(admin_token.access_token).replace(/"/g, '');
```
It removes any unwanted quotation marks.
