### ISSUE TITLE
Creating input front-end for merchant

### ISSUE THREAD

**Issue by MaddyLIN** [Arcadier/Plug-In-support#6]
**Your issue/question:**
I'm creating a plug-in where I would need an additional box in the position shown in the first Screenshot below. Could you tell me how I can do that?

**What you expect to achieve**
I want that box to be called Recommended Retail Price, and it will be a text input field. It's located on the item upload page on the merchant's page.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/49678975/57357119-cd08ec00-71a4-11e9-8e7a-0c1827bf8de8.png)

**Comment by Arcadier** [comment]
Hey Maddy, before we help you, can you tell us how are you intending to insert whichever code into your marketplace? Is it through custom code or as plug-in?

**Comment by MaddyLIN** [comment]
I'm trying to do this using custom code for now, and my marketplace is chocopups.sandbox.arcadier.io

**Comment by Chloe-blue** [comment]
Hey Maddy, I've done this before. Try using jQuery:
This is what the page looks like originally:
```html
<div class="un-inputs">
  <div class="item-form-group">
  </div>
  <div class="item-form-group">
    <div class="col-md-6">
      <label>Item Name</label>
      <input/>
    </div>
  </div>
<div class="item-form-group">
    <div class="col-md-6">
      <label>Price</label>
      <input/>
    </div>
  </div>
<div class="item-form-group">
    <div class="col-md-6">
      <label>SKU</label>
      <input/>
    </div>
  </div>
<div class="item-form-group">
    <div class="col-md-12">
      <label>Item Description</label>
      <input/>
    </div>
  </div>
</div>
```
And you want your box to appear after the SKU field and before the Item description field. So you will have to select the 3rd 'div' child element from the div with class ="un-inputs".
The code is:
```javascript 
$( ".un-inputs div:nth-child(3)" ).append("<div class=\"col-md-6\">Whatever</div>");
```
Replace "Whatever" with your field's code.

**Comment by MaddyLIN** [comment]
Hey Chloe,

I did it and it worked but there's a slight misalignment as shown in the screenshot. What am I doing wrong?

![image](https://user-images.githubusercontent.com/49678975/57359050-4f93aa80-71a9-11e9-9542-aa866f3a7144.png)

this is the exact code I'm writing
```javascript
$( ".un-inputs div:nth-child(3)" ).append("<div class=\"col-md-6\">Recommended Retail Price</div>").append("<div class=\"col-md-6\"><input type=\"text\" name=\"rrp\"></div>);
```

**Comment by Chloe-blue** [comment]
Try this instead
```javascript
$( ".un-inputs div:nth-child(3)" ).append("<div class=\"col-md-6\"><label>Recommended Retail Price</label><input type=\"text\" name=\"rrp\"></div>");
```

**Comment by MaddyLIN** [comment]
@Chloe-blue Thank You. It worked.
