### ISSUE TITLE
problem with JSON data structure after response

### ISSUE THREAD

**Issue by ABHINAV112** [Arcadier/Plug-In-support#7]
**Your issue/question:**
After assigning JSON objects to a JSON the same change is made to every inner JSON instead of only the required JSON which should be changed.

**What you expect to achieve**
Each assignment should only be made to the required JSON object and not every inner JSON object.

**What happens instead**
Every inner JSON object is updated at the same time when only one of them should get updated.

**Screenshots**
![Screenshot from 2019-06-10 10-49-48](https://user-images.githubusercontent.com/42908304/59169757-1f577700-8b6e-11e9-9cca-e281048fa3a2.png)
![Screenshot from 2019-06-10 10-50-05](https://user-images.githubusercontent.com/42908304/59169758-1ff00d80-8b6e-11e9-895d-08bbd85a5114.png)

**Your system/software details**
Running an Ubuntu 18.04 LTS

**Comment by naseer2426** [comment]
Try initializing the "TimeData" inside the for loop. 

Since you assigned "TimeData" outside the for loop in line 23, when you are assigning megaTimeData[i] to TimeData in line 27, it essentially references megaTimeData[i] to the same memory location as "TimeData". That is the reason your changes are reflected everywhere in your JSON file

**Comment by ABHINAV112** [comment]
I did that but now i changed up the structure of the inner JSON object, and now it's not working. I am now getting an error which says assigning a property to an undefined object.

![Screenshot from 2019-06-10 11-23-55](https://user-images.githubusercontent.com/42908304/59170679-5891e600-8b72-11e9-8dcb-a51ff89c420d.png)
![Screenshot from 2019-06-10 11-24-08](https://user-images.githubusercontent.com/42908304/59170680-5891e600-8b72-11e9-9810-92d31f4c66eb.png)

**Comment by naseer2426** [comment]
You have used i in both the inner and outer for loops. I think that is what is causing the problem. Try changing inner for loop variable to j.

**Comment by ABHINAV112** [comment]
Oh ok made the changes and adjusted some code it's working now. 

Thanks
