### ISSUE TITLE
Error in retrieving Admin ID

### ISSUE THREAD

**Issue by naseer2426** [Arcadier/Plug-In-support#8]
**Describe the bug**
When I try to retrieve Admin ID using getElementById("userGuid") it returns a null.

**Expected behavior**
The function should have returned a value

**Screenshots**

My code:
![code](https://user-images.githubusercontent.com/35726629/59170203-28e1de80-8b70-11e9-84d2-ef5c5d6c2b5b.JPG)

This is the error that I get
![consoleError](https://user-images.githubusercontent.com/35726629/59170105-b8d35880-8b6f-11e9-8b8b-3eb0ed2b2e8a.JPG)

![SourcesErr](https://user-images.githubusercontent.com/35726629/59170127-cd175580-8b6f-11e9-92cf-4b14a0031e8e.JPG)

But when I check the html, I can clearly see there is a hidden tag with id = "userGuid".
![userGuidProof](https://user-images.githubusercontent.com/35726629/59170179-0e0f6a00-8b70-11e9-8bd3-b2ee90510216.JPG)

**Specifications:**
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by ABHINAV112** [comment]
This seems to be unusual can you try moving the adminID inside the displayAdminID function and then checking.

**Comment by naseer2426** [comment]
I tried that, Im still facing the same error

The new code:
![changedCode1](https://user-images.githubusercontent.com/35726629/59171109-179ad100-8b74-11e9-8c10-03d132033fa5.JPG)

Console:
![error1](https://user-images.githubusercontent.com/35726629/59171126-28e3dd80-8b74-11e9-8237-476e6617aece.JPG)

![codeerror1](https://user-images.githubusercontent.com/35726629/59171137-3e590780-8b74-11e9-8cc3-bc9a416e7b40.JPG)

**Comment by ABHINAV112** [comment]
try using jQuery to run the function when the DOM renders.
```javascript
$("document").ready(function(){
  displayAdminID();
});
```

**Comment by naseer2426** [comment]
I used the following code and it worked 😄 
![worked](https://user-images.githubusercontent.com/35726629/59171653-8e38ce00-8b76-11e9-9d2e-2e032887a1f6.JPG)

```javascript
function getCookie(name){
  var value = '; ' + document.cookie;
  var parts = value.split('; ' + name + '=');
  if (parts.length === 2) {
      return parts.pop().split(';').shift();
  }
}

var baseURL = window.location.hostname;
var token = getCookie('webapitoken');
var admin;

$(document).ready(function(){
  displayAdminID();
})



function displayAdminID()
{
  admin = document.getElementById("userGuid").value;
  console.log(admin);
  var displayInput = document.getElementById("adminID");
  displayInput.value = admin;
}
```

**Comment by naseer2426** [comment]
Why does this happen tho? What was then reason my previous code didn't work?

**Comment by ABHINAV112** [comment]
This happens because the DOM doesn't render with the 'userGuid' tag preloaded. The userGuid is rendered only after some time. Putting your function inside the jQuery waits for the DOM to render before running the script.
